version: '3.8'

# 國考法律題型分析系統 - Docker Compose Configuration
# 支援服務: PostgreSQL, Redis, API

services:
  # PostgreSQL Database with pgvector extension
  postgresql:
    image: docker.io/pgvector/pgvector:pg17
    container_name: legal-analysis-postgresql
    restart: unless-stopped
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: 'legal_analysis_db'
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/01-init.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin -d legal_analysis_db']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
      - '5432:5432'
    networks:
      - legal-analysis-network

  # Redis Cache for session and AI analysis cache
  redis:
    image: redis:7-alpine
    container_name: legal-analysis-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 3s
      retries: 5
    ports:
      - '6379:6379'
    networks:
      - legal-analysis-network

  # FastAPI Application (for production deployment)
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: legal-analysis-api
    restart: unless-stopped
    environment:
      - APP_NAME=國考法律題型分析系統
      - ENVIRONMENT=production
      - DEBUG=false
      - DATABASE_URL=postgresql://admin:admin@postgresql:5432/legal_analysis_db
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=${SECRET_KEY:-default-secret-key-change-in-production}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LOG_LEVEL=INFO
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - '8000:8000'
    networks:
      - legal-analysis-network
    volumes:
      - ./data/uploads:/app/data/uploads
      - ./logs:/app/logs
      - ./data:/app/data
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # PgAdmin for database management (development only)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: legal-analysis-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@legal-analysis.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - '5050:80'
    networks:
      - legal-analysis-network
    depends_on:
      - postgresql
    profiles:
      - dev

networks:
  legal-analysis-network:
    driver: bridge

volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local